version: "3.9"

services:
  app:
    build: .
    container_name: gym_mvp_app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/gym_mvp
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: gym_mvp_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
